---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: ubuntu
  pull: always
  image: enros/packer-build-qemu:latest
  commands:
    - build ubuntu-focal.json
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - "refs/tags/*"
