---
kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: ubuntu
  pull: if-not-exists
  image: enros/packer-build-qemu:latest
  privileged: true
  volumes:
    - name: kvm
      path: /dev/kvm
  commands:
    - PACKER_LOG=1 packer build ubuntu-focal.json
  environment:
    VAGRANT_CLOUD_TOKEN:
      from_secret: VAGRANT_CLOUD_TOKEN
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - "refs/tags/*"
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel: pipeline
volumes:
- name: kvm
  host:
    path: /dev/kvm