name: build ubuntu-focal vagrant image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - 
        run: sudo apt-get update 
      - 
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install qemu qemu-kvm libvirt-daemon bridge-utils virt-manager virtinst cpu-checker kmod
      - 
        run: sudo kvm-ok
      - 
        uses: actions/checkout@v1
      - 
        name: Pull the Docker Image
        run: docker pull enros/packer-build-qemu:latest

