name: build ubuntu-focal vagrant image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v1
      - 
        name: Packer qemu build
        uses: enr0s/packer-qemu-action@v1.1
        with:
          templateFile: ubuntu-focal.json
        env:
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
