---
name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: /github/workspace/ubuntu-focus.json

      # build artifact
      - name: Build Artifact
        env:
          VAGRANT_CLOUD_TOKEN:  ${{ secrets.VAGRANT_CLOUD_TOKEN }}
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: /github/workspace/ubuntu-focus.json
